export const stakeholderList = [
  'Building data owners',
  'Building design professionals (architects, engineers)',
  'Building design / LCA tool developers and providers',
  'Building LCA consultants and service providers',
  'Building users',
  'Civil society',
  'Clients / inventors / owners (of building data)',
  'Construction companies',
  'Construction product manufacturers',
  'Facility managers',
  'Financial service providers / insurance companies',
  'Funding (system) developers and providers',
  'Inter / National standardization bodies',
  'Media representatives',
  'Policy and law makers, regulators (national, local)',
  'Product LCA database developers',
  'Product LCA/EPD data developers',
  'Researchers (basic / applied building LCA research)',
  'Surveyors, valuation professionals',
  'Sustainability assessment system developers and providers',
  'Sustainability assessors/auditors',
  'Sustainability / ESG consultants and service providers',
]
