# Simple workflow for deploying static content to GitHub Pages
name: Deploy Website to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main
      - stage
  pull_request:
    branches:
      - main
      - stage

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NODE_VERSION: '20.x'
  REGISTRY: globalbuildingdatainitiative
  CONTAINER_NAME: web-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: NPM Install
        run: npm ci

      - name: Check
        run: npm run check

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
        env:
          VITE_APP_NAME: GBDI
          VITE_GRAPHQL_API_DOMAIN: "https://${{ (github.ref_name != 'main' && 'stage.') || ''}}api.gbdi.io"
          VITE_WEB_DOMAIN: "https://${{ (github.ref_name != 'main' && 'stage.') || ''}}app.gbdi.io"
          VITE_AUTH_API_DOMAIN: "https://${{ (github.ref_name != 'main' && 'stage.') || ''}}api.gbdi.io"
          VITE_AUTH_API_PATH: /api/auth
          VITE_AUTH_WEB_PATH: /auth

      - name: Upload artifact for deployment job
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: gbdi-app
          path: ./dist
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: gbdi-app
          path: dist

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io/${{ inputs.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        run: docker build -t ghcr.io/${{ env.REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.run_number }} .

      - name: Tag Image
        run: docker tag ghcr.io/${{ env.REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.run_number }} ghcr.io/${{ env.REGISTRY }}/${{ env.CONTAINER_NAME }}:${{ github.ref_name }}

      - name: Push Image
        if: github.event_name != 'pull_request'
        run: docker push --all-tags ghcr.io/${{ env.REGISTRY }}/${{ env.CONTAINER_NAME }}